lib/podio/models/item.rb
Added attributes and options arguments to the delete method.
Useful for example to use { silent: true } option
=> Podio::Item.delete attributes and options

lib/podio/models/tag.rb
6 additional tag methods so that all are covered in the ruby API. Small christmas gift from Belgium ;)
=> Extra tag methods

lib/podio/models/embed.rb
Option was described in documentation but not available in the gem
=> added delayed option for embed.create

lib/podio/models/email_subscription_setting.rb
I'm just doing a new branch rather than rolling back to a previous head.
=> Rolling back change. Story ref: 2965

lib/podio/models/email_subscription_setting.rb
Revert "Rolling back change. Story ref: 2965"
This reverts commit 0fd4fd0b646e6d6ddb52731693c886aa2ba34665.
=> New properties for notification options.

lib/podio/models/user.rb, podio.gemspec
We can sit on this PR for a bit, but I wanted to get the changes out there
=> New property for sharefile-only users. Story ref: 3228

lib/podio/models/application.rb
Change for paywall on add item.
=> Added item_accounting_info in app modal

lib/podio/models/organization.rb
Updated with the new API end point URL for reporting page.
Will merge once API changes are merged. 
Changes are there on frontend-rails repo as well.
=> updated url for metric page changes

lib/podio/client.rb, lib/podio/error.rb, lib/podio/middleware/error_response.rb
Continue with authentication by submitting the code along with the nonce.
=> [POD-380] Continue with 2SV

lib/podio/models/invoice.rb
[POD-499](https://issues.citrite.net/browse/POD-499)
=> Added methods for calling the new invoice APIs.

lib/podio/error.rb
=> Add maintenance error

lib/podio/models/contract.rb
New cancellation endpoint for SFDC and introduction of new attribute for effective_cancellation_date
=> New cancellation endpoint

lib/podio/models/invoice.rb
Making use of the cached calls
=> Adding new method to get the invoice details

lib/podio/models/contract.rb
Changes to propagate FCD value from API to consuming systems. Here the consumer of this change is Admin contract view
POD-2483
=> Changes to support fcd

lib/podio/models/user.rb
- Added attribute accessor tier to user model
- new source tier api call method
POD-3923
NA
Local
=> Added attribute accessor tier and new source tier api call method

lib/podio/models/contract.rb
fix for nil not a symbol error
=> Pod 3923 bug fix 2

lib/podio/models/space_invitation.rb
https://issues.citrite.net/browse/POD-4742
added new methods
=> [POD-4742] Invite user as Employee or Client

lib/podio/models/space_invitation.rb
=> Revert "[POD-4742] Invite user as Employee or Client"

lib/podio/models/contract.rb
https://issues.citrite.net/browse/POD-4971
-extended a model with new attribute
=> [POD-4971] [FE] limit migrated licenses form

lib/podio/models/grant.rb, lib/podio/models/space.rb
New Route added
- returns list of users with whom the apps have been shared
=> [POD-4803] - Show app shared user list in workspace management

lib/podio/models/organization.rb
Added an additional trial_expired_on property to org
https://issues.citrite.net/browse/POD-5304
=> POD-5304: Added expiration date to Org model

lib/podio/models/contract_accounting.rb
-added vat_id to the contract model
https://issues.citrite.net/browse/POD-5512
=> [POD-5512] Integrate ECom API to support the functionality of "Change Billing information" for SFDC provisioned org.

lib/podio/models/invoice.rb
=> [POD-5510] Support the functionality of "View Billing invoices" 

lib/podio/models/contract.rb
Added method to get Ecom prices
=> POD-5581: Ecom plans - from ecom API

lib/podio.rb, lib/podio/models/ecom_plan.rb
- added EcomPlan model with methods to fetch
=> POD-5583: Added EcomPlan model
